---
- name: Init data directory
  file:
    path: "{{ data_path }}"
    state: directory
    recurse: yes

- name: Init data directory Nuxeo
  file:
    path: "{{ data_path }}/data/nuxeo"
    state: directory
    recurse: yes
  when: "nuxeo"

- name: Copy the nuxeo instance clid
  copy:
    src: "{{ instance_clid }}"
    dest: "{{ data_path }}/data/nuxeo/instance.clid"
    mode: 0644

- name: Init data directory Elastic
  file:
    path: "{{ data_path }}/data/elastic"
    state: directory
    recurse: yes
  when: "elastic"

- name: Copy the nuxeo init
  copy:
    src: nuxeo
    dest: "{{ data_path }}"
  when: "nuxeo"

- name: Generate the nuxeo.conf file
  template:
    src: nuxeo.conf.j2
    dest: "{{data_path}}/nuxeo/nuxeo.conf"
  when: "nuxeo"

- name: Copy the mongo init
  copy:
    src: mongo
    dest: "{{ data_path }}"
  when: "mongo"

- name: Copy the postgres init
  copy:
    src: postgres
    dest: "{{ data_path }}"
  when: "postgres"

- name: Copy the graphite init
  copy:
    src: graphite
    dest: "{{ data_path }}"
  when: "graphite"

- name: Copy the grafana init
  copy:
    src: grafana
    dest: "{{ data_path }}"
  when: "grafana"

- name: Copy the stream init
  copy:
    src: stream
    dest: "{{ data_path }}"
    mode: 0755
  when: "stream"

- name: Copy kafkaHQ init
  copy:
    src: kafkahq
    dest: "{{ data_path }}"
  when: "kafkahq"

- name: Generate the docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{data_path}}/docker-compose.yml"

- name: Copy scripts
  copy:
    src: bin
    dest: "{{ data_path }}"
    mode: preserve

- name: Generate the esync conf
  template:
    src: esync.conf.j2
    dest: "{{data_path}}/bin/esync.conf"
